threads = 2
verbose = false
retries = 15
subdomains = false
parameters = false
providers = ["wayback", "commoncrawl", "otx", "urlscan", "github"]
blacklist = ["css","txt","jpg", "jpeg", "png", "gif", "svg", "woff", "woff2", "ttf", "otf", "eot", "ico", "mp4", "mp3", "avi", "mov", "wmv", "flv", "mkv", "zip", "tar", "gz", "bz2", "7z", "rar", "pdf", "doc", "docx", "xls", "xlsx", "ppt", "pptx", "exe", "dmg", "iso"]
json = false

[urlscan]
  apikey = ""

[filters]
  from = ""
  to = ""
  matchstatuscodes = []
  matchmimetypes = []
  filterstatuscodes = []
  filtermimetypes = ["image/png", "image/jpg", "image/svg+xml"]
